// import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import Loading from "./loading";
import Head from "next/head";
import { LanguageProvider } from "@/contexts/LanguageContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Welcome to Kuber Temple",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Suspense fallback={<Loading />}>
      <body className="relative  font-rubik">
        <LanguageProvider>
          {children}
        </LanguageProvider>
      </body>
      </Suspense>
    </html>
  );
}
